version: '3'

services:
  app:
    build:
      context: app
    container_name: app
    tty: true
    ports:
      - "8080:8080"
    networks:
      - node-network
  nginx:
    build:
      context: nginx
    container_name: nginx
    networks:
      - node-network
    ports:
      - "3000:80"
    restart: always
  server_1:
    build:
      context: server
    container_name: server_1
    tty: true
    environment:
      - POD_NAME=SERVER_1
    networks:
      - node-network
  server_2:
    build:
      context: server
    container_name: server_2
    tty: true
    environment:
      - POD_NAME=SERVER_2
    networks:
      - node-network
  server_3:
    build:
      context: server
    container_name: server_3
    tty: true
    environment:
      - POD_NAME=SERVER_3
    networks:
      - node-network

networks:
  node-network:
    driver: bridge
